### ISSUE TITLE
how long will it run?

### ISSUE THREAD

**Issue by kalluwa** [weiquanmao/PCF#1]
Hi Wei, thanks for sharing your great work, i just test the project in debug mode, and wait for 90mins, but it is still running, so how long will it take when "PCF.exe" finished.

30mins has passed in release mode and it seems not gonna stop.

**Comment by weiquanmao** [comment]
There is a bug in the current test code. Since the output paths (`SynOutputDir` and `ReconOutputDir`) are the same as the input paths (`SynInputDir` and `ReconInputDir`), the generated results are processed again, resulting in **an infinite loop**. 

To fix it, please change the output paths to be different from the input paths.

**Comment by kalluwa** [comment]
thanks for reply,
it finished after i modified the output dir.
